// app/layout.js
export const metadata = {
  title: 'Testing',
  description: 'Generated by create next app for testing purpose',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
    
      </head>

      <body>
        {children}
        <script src="//code.tidio.co/wlvmvyfz4ndkaewbo61pme0lhhsfpin8.js" async></script>
      </body>
    </html>
  );
}
