// app/layout.js
export const metadata = {
  title: 'Testing',
  description: 'Generated by create next app for testing purpose',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Metadata and other head elements */}
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
